### ISSUE TITLE
Change azure-cli executor image

### ISSUE THREAD

**Issue by just-evgenyevlampev** [CircleCI-Public/azure-aks-orb#11]
### Orb version

0.2.1

### What happened

Microsoft has changed their namespace of the Docker Hub, and it causes an issue to this orb for pulling a docker image.

### Expected behavior

The orb uses the latest version of `azure-cli` from `mcr.microsoft.com/azure-cli`

Basically, the same fix should be applied as here https://github.com/CircleCI-Public/azure-cli-orb/pull/11

**Comment by just-yauhenikaleinikau** [comment]
@lokst Hi! There is still an issue with the pipeline and I believe it's connected with the integration tests that you have guys for this orb. Is there any news around this?

**Comment by lokst** [comment]
@just-yauhenikaleinikau We were able to publish the changes in https://github.com/CircleCI-Public/azure-aks-orb/pull/12 in a separate workflow, bypassing the issues with the integration tests. Could you try using version `0.3.0` of the orb?

**Comment by just-yauhenikaleinikau** [comment]
@lokst thanks for your answer. Really appreciate for you help. But looks like we have the same issue that was in integration tests.
Here is the log:
![image](https://user-images.githubusercontent.com/68378244/122380062-280a9100-cf70-11eb-9e2e-ac49cfbaf9b2.png)

And it stucks here :(

**Comment by just-yauhenikaleinikau** [comment]
@lokst thank you very much! It does work with new version! Appreciate your help with that!
