### ISSUE TITLE
Can't specify `service-principal` and `client-secret` with environment variables

### ISSUE THREAD

**Issue by bingosummer** [CircleCI-Public/azure-aks-orb#3]
The default of `service-principal` and `client-secret` should be the environment variable `AZURE_SP` and `AZURE_SP_PASSWORD`.

**Comment by bingosummer** [comment]
@lokst could you please have a look?

**Comment by lokst** [comment]
@bingosummer That makes sense, I should be able to make the change in the coming week but let me know if you'd like to open a PR!

**Comment by bingosummer** [comment]
@lokst Thanks. I just submitted a PR, but I don't know clearly how to test it locally. I assume the PR checks can help test it.
